In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from skimage import transform

tf.logging.set_verbosity(tf.logging.INFO)

# Load data
x_train = np.load('exam2_train_x.npy').astype(np.float32)
y_train = np.load('exam2_train_y.npy').astype(int)
# x_train = x_train/255.

x_test = np.load('exam2_test_x.npy').astype(np.float32)
y_test = np.load('exam2_test_y.npy').astype(int)
# x_test = x_test/255.

In [2]:
def gen_augmented_data(x, y):
    
    new_x_imgs = []
    new_y = []
    for x_train, y_train in zip(x, y):

        cw = transform.rotate(image=x_train, angle=15., mode='edge', resize=False, preserve_range=True)
        ccw = transform.rotate(image=x_train, angle=-15., mode='edge', resize=False, preserve_range=True)

        # new_x_imgs.append(np.flipud(x_train))
        # new_y.append(y_train)
        new_x_imgs.append(np.fliplr(x_train))
        new_y.append(y_train)
        new_x_imgs.append(cw)
        new_y.append(y_train)
        new_x_imgs.append(ccw)
        new_y.append(y_train)

    return new_x_imgs, new_y

In [11]:
def conv_model(features, mode, labels):
    input_layer = tf.reshape(features["x"], [-1, 64, 64, 3])
    
    c1 = tf.layers.conv2d(inputs=input_layer, filters=32, kernel_size=[5, 5], padding='same',
                          activation=tf.nn.relu)
    p1 = tf.layers.max_pooling2d(inputs=c1, pool_size=[2, 2], strides=2)
    
    c2 = tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5, 5], padding='same',
                          activation=tf.nn.relu)
    p2 = tf.layers.max_pooling2d(inputs=c2, pool_size=[2, 2], strides=2)
    
    # c3 = tf.layers.conv2d(inputs=p2, filters=128, kernel_size=[3, 3], padding='same',
    #                       activation=tf.nn.relu)
    # p3 = tf.layers.max_pooling2d(inputs=c3, pool_size=[2, 2], strides=2)
    
    # c4 = tf.layers.conv2d(inputs=p3, filters=256, kernel_size=[3, 3], padding='valid',
    #                       activation=tf.nn.relu)
    # p4 = tf.layers.max_pooling2d(inputs=c4, pool_size=[2, 2], strides=2)
    
    # c4 = tf.layers.conv2d(inputs=p3, filters=64, kernel_size=[4, 4], padding='same',
    #                       activation=tf.nn.relu, strides=1)
    # p4 = tf.layers.max_pooling2d(inputs=c4, pool_size=[2, 2], strides=1)
    
    a5 = tf.reshape(p2, [-1, 16*16*64])
    z5 = tf.layers.dense(a5, units=1024, activation=tf.nn.relu)
    z5 = tf.layers.dropout(inputs=z5, rate=0.5, training=(mode == tf.estimator.ModeKeys.TRAIN))
    
    z6 = tf.layers.dense(z5, units=512, activation=tf.nn.relu)
    z6 = tf.layers.dropout(inputs=z6, rate=0.5, training=(mode == tf.estimator.ModeKeys.TRAIN))
    
    z7 = tf.layers.dense(z6, units=6, activation=tf.nn.sigmoid)

    onehot = tf.one_hot(indices=tf.cast(labels, tf.int32), depth=6)

    loss = tf.losses.softmax_cross_entropy(onehot_labels=onehot, logits=z7)
    
    predictions = {'classes': tf.argmax(input=z7, axis=1),
                   'probabilities': tf.nn.softmax(z7, name="softmax_tensor")}
    
    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)
    
    if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
        train_op = optimizer.minimize(loss=loss, 
                                      global_step=tf.train.get_global_step())
        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

    eval_metric_ops = {"accuracy": tf.metrics.accuracy(labels=labels, predictions=predictions["classes"])}
    return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)

In [4]:
newx, newy = gen_augmented_data(x_train, y_train)
x_train = np.append(x_train, newx, axis=0).astype(np.float32)
y_train = np.append(y_train, newy, axis=0).astype(np.int)

print(x_train.shape)

x_train = x_train/255.

(4080, 64, 64, 3)


In [14]:
tf.set_random_seed(5)

print(x_train.shape)

clf = tf.estimator.Estimator(model_fn=conv_model, model_dir='model')

log_hook = tf.train.LoggingTensorHook(tensors={"probabilities": "softmax_tensor"}, every_n_iter=100)

train_input = tf.estimator.inputs.numpy_input_fn(x={'x': x_train}, 
                                                 y=y_train, batch_size=100, 
                                                 num_epochs=None, shuffle=True)
clf.train(input_fn=train_input, steps=400, hooks=[log_hook])

(4080, 64, 64, 3)
INFO:tensorflow:Using default config.


INFO:tensorflow:Using config: {'_model_dir': 'model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000023589586630>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


INFO:tensorflow:Create CheckpointSaverHook.


INFO:tensorflow:Restoring parameters from model\model.ckpt-200


INFO:tensorflow:Saving checkpoints for 201 into model\model.ckpt.


INFO:tensorflow:probabilities = [[0.14494063 0.14467445 0.24894106 0.13988867 0.15806924 0.16348588]
 [0.10609204 0.10609198 0.10609198 0.10609209 0.28724504 0.28838697]
 [0.12294444 0.1218145  0.12182029 0.22428301 0.12645577 0.28268197]
 [0.10632072 0.28576633 0.28894618 0.10634518 0.106312   0.10630962]
 [0.12907574 0.12907554 0.12907971 0.3506876  0.12908766 0.13299367]
 [0.12464755 0.12464755 0.12464755 0.33882713 0.1247985  0.16243179]
 [0.12821521 0.12811154 0.13732886 0.13261028 0.1283038  0.34543028]
 [0.10688877 0.28322056 0.28988266 0.10666577 0.10668256 0.10665964]
 [0.12020255 0.11986796 0.12001205 0.12790568 0.18757285 0.3244389 ]
 [0.10597674 0.28801304 0.28806144 0.10599938 0.10597527 0.10597417]
 [0.10597369 0.28801012 0.28806    0.10600867 0.10597374 0.10597369]
 [0.17270686 0.23212083 0.21250996 0.11951911 0.11953471 0.14360851]
 [0.3503725  0.12973526 0.12978475 0.13050564 0.1297408  0.1298611 ]
 [0.13198066 0.13722292 0.15936747 0.13178053 0.30264768 0.13700074]
 [

INFO:tensorflow:loss = 1.2147787, step = 201


INFO:tensorflow:global_step/sec: 1.20858


INFO:tensorflow:probabilities = [[0.35217994 0.12955993 0.12958032 0.12956019 0.12955981 0.1295598 ]
 [0.12951793 0.12951499 0.12951718 0.12959543 0.12980162 0.35205284]
 [0.12117113 0.32812423 0.17424525 0.13431175 0.12107841 0.12106914]
 [0.1283145  0.1283375  0.12833284 0.34803152 0.12853467 0.13844903]
 [0.1267918  0.12684007 0.15032308 0.12675819 0.34242985 0.12685704]
 [0.12689538 0.3445306  0.14795719 0.12692244 0.12684715 0.12684712]
 [0.12883662 0.3486043  0.13674799 0.12864542 0.12858656 0.12857918]
 [0.1295603  0.1295603  0.1295603  0.12957142 0.12956694 0.35218075]
 [0.13264999 0.12908426 0.12979159 0.35044372 0.12901539 0.12901501]
 [0.35160166 0.12934704 0.12934707 0.12934707 0.12934704 0.13101012]
 [0.12474608 0.12970491 0.33841798 0.12499139 0.155998   0.12614171]
 [0.12866156 0.34970957 0.13260858 0.13170095 0.12865968 0.12865968]
 [0.12949318 0.12949318 0.1295117  0.13000353 0.35199887 0.12949955]
 [0.11055158 0.2815644  0.27498093 0.11241568 0.11024468 0.11024276]
 [

INFO:tensorflow:loss = 1.1723671, step = 301 (82.748 sec)


INFO:tensorflow:global_step/sec: 1.26549


INFO:tensorflow:probabilities = [[0.35218745 0.12956253 0.12956253 0.12956253 0.12956253 0.12956253]
 [0.12950571 0.12950571 0.12950572 0.12950571 0.35203302 0.12994418]
 [0.12956035 0.12956038 0.12956034 0.3521812  0.12957351 0.12956426]
 [0.12955911 0.12955911 0.12955911 0.12955911 0.12958533 0.3521782 ]
 [0.34906843 0.12841517 0.12841517 0.12841517 0.12841517 0.13727093]
 [0.35218745 0.12956253 0.12956253 0.12956253 0.12956253 0.12956253]
 [0.3520594  0.12960428 0.1296135  0.12965748 0.12953098 0.12953426]
 [0.11850499 0.24631901 0.13117826 0.26698318 0.11850777 0.11850681]
 [0.35072863 0.12902594 0.12902594 0.13316773 0.12902594 0.12902594]
 [0.14962347 0.13178319 0.13178311 0.13649875 0.13178311 0.31852832]
 [0.10903954 0.10903954 0.10903954 0.26767468 0.10912698 0.29607964]
 [0.35218745 0.12956253 0.12956253 0.12956253 0.12956253 0.12956253]
 [0.1263689  0.12637946 0.13469605 0.34249428 0.14369237 0.12636898]
 [0.12943704 0.12943694 0.1294372  0.12943788 0.13041261 0.35183832]
 [

INFO:tensorflow:loss = 1.123713, step = 401 (81.160 sec)


INFO:tensorflow:global_step/sec: 1.2026


INFO:tensorflow:probabilities = [[0.35207015 0.12958065 0.12957068 0.12963714 0.12957068 0.12957068]
 [0.35216892 0.12956293 0.12956369 0.12956242 0.12956372 0.12957828]
 [0.3292507  0.12163033 0.12141008 0.12140924 0.12141164 0.18488812]
 [0.12955435 0.35216266 0.12962289 0.1295534  0.1295534  0.1295534 ]
 [0.12938382 0.12935016 0.12935019 0.12935106 0.13110594 0.35145876]
 [0.12907995 0.129081   0.13311374 0.35049644 0.12908831 0.12914057]
 [0.12956248 0.12956248 0.12956254 0.12956248 0.35218734 0.12956262]
 [0.10722356 0.10722356 0.2874711  0.10736109 0.28349727 0.10722356]
 [0.12956251 0.12956251 0.35218742 0.12956251 0.12956251 0.12956251]
 [0.12956215 0.35218632 0.12956515 0.12956212 0.12956212 0.12956212]
 [0.12955928 0.12955928 0.12955928 0.12955928 0.3521786  0.1295843 ]
 [0.12931709 0.13122274 0.3514754  0.12931739 0.1293504  0.12931708]
 [0.1295597  0.1295597  0.12955974 0.12958159 0.12955971 0.35217956]
 [0.34998658 0.12877116 0.13498048 0.12875393 0.12875393 0.12875393]
 [

INFO:tensorflow:loss = 1.0846535, step = 501 (81.010 sec)


INFO:tensorflow:Saving checkpoints for 600 into model\model.ckpt.


INFO:tensorflow:Loss for final step: 1.090927.


In [15]:
predict_input = tf.estimator.inputs.numpy_input_fn(
    {'x': x_test}, y=y_test, num_epochs=1, shuffle=False)
results = clf.evaluate(input_fn=predict_input)

print(results)

INFO:tensorflow:Starting evaluation at 2018-04-15-08:20:44


INFO:tensorflow:Restoring parameters from model\model.ckpt-600


INFO:tensorflow:Finished evaluation at 2018-04-15-08:20:45


INFO:tensorflow:Saving dict for global step 600: accuracy = 0.92777777, global_step = 600, loss = 1.1324644


{'accuracy': 0.92777777, 'loss': 1.1324644, 'global_step': 600}
